// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UyeIsyeriBasvuru.Data;

#nullable disable

namespace UyeIsyeriBasvuru.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260702070608_InitialCleanDb")]
    partial class InitialCleanDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UyeIsyeriBasvuru.Models.UyeIsyeriBankaBilgi", b =>
                {
                    b.Property<long>("BankaBilgiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("BankaBilgiId"));

                    b.Property<string>("BankaAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("BasvuruId")
                        .HasColumnType("bigint");

                    b.Property<long>("BasvuruId1")
                        .HasColumnType("bigint");

                    b.Property<string>("HesapNo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("HesapSahibi")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Iban")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("nvarchar(26)");

                    b.HasKey("BankaBilgiId");

                    b.HasIndex("BasvuruId");

                    b.HasIndex("BasvuruId1");

                    b.ToTable("UyeIsyeriBankaBilgi", (string)null);
                });

            modelBuilder.Entity("UyeIsyeriBasvuru.Models.UyeIsyeriBasvuruModel", b =>
                {
                    b.Property<long>("BasvuruId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("BasvuruId"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<string>("BasvuruDurumu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BasvuruNO")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("BasvuruTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("MusteriTipi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("OnayTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RedNedeni")
                        .HasColumnType("int");

                    b.HasKey("BasvuruId");

                    b.ToTable("UyeIsyeriBasvuru", (string)null);
                });

            modelBuilder.Entity("UyeIsyeriBasvuru.Models.UyeIsyeriCalismaSarti", b =>
                {
                    b.Property<long>("CalismaSartiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CalismaSartiId"));

                    b.Property<long>("BasvuruId")
                        .HasColumnType("bigint");

                    b.Property<long>("BasvuruId1")
                        .HasColumnType("bigint");

                    b.Property<string>("BasvuruTipi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsOzelYetkiFlag")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTaksitSecim")
                        .HasColumnType("bit");

                    b.Property<string>("MarkaPaylasimTipi")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("OzelYetkiVerenSicil")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TaksitliCalismaSekli")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TaksitliPuanOrani")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<string>("TekOdemeCalismaSekli")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TekOdemePuanOrani")
                        .HasColumnType("decimal(18, 3)");

                    b.HasKey("CalismaSartiId");

                    b.HasIndex("BasvuruId");

                    b.HasIndex("BasvuruId1");

                    b.ToTable("UyeIsyeriCalismaSarti", (string)null);
                });

            modelBuilder.Entity("UyeIsyeriBasvuru.Models.UyeIsyeriDokuman", b =>
                {
                    b.Property<long>("DokumanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("DokumanId"));

                    b.Property<long>("BasvuruId")
                        .HasColumnType("bigint");

                    b.Property<long>("BasvuruId1")
                        .HasColumnType("bigint");

                    b.Property<string>("DokumanTipi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DosyaAdi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DosyaYolu")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("YuklemeTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("DokumanId");

                    b.HasIndex("BasvuruId");

                    b.HasIndex("BasvuruId1");

                    b.ToTable("UyeIsyeriDokuman", (string)null);
                });

            modelBuilder.Entity("UyeIsyeriBasvuru.Models.UyeIsyeriDurumLog", b =>
                {
                    b.Property<long>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LogId"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("BasvuruId")
                        .HasColumnType("bigint");

                    b.Property<long>("BasvuruId1")
                        .HasColumnType("bigint");

                    b.Property<string>("EskiDurum")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("IslemTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("IslemYapanKullanici")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("YeniDurum")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("LogId");

                    b.HasIndex("BasvuruId");

                    b.HasIndex("BasvuruId1");

                    b.ToTable("UyeIsyeriDurumLog", (string)null);
                });

            modelBuilder.Entity("UyeIsyeriBasvuru.Models.UyeIsyeriFirmaBilgi", b =>
                {
                    b.Property<long>("FirmaBilgiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("FirmaBilgiId"));

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("BasvuruId")
                        .HasColumnType("bigint");

                    b.Property<long>("BasvuruId1")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FaaliyetKonusu")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("FirmaUnvan")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Il")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("KurulusTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("MersisNo")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VergiDairesi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VergiNo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("FirmaBilgiId");

                    b.HasIndex("BasvuruId");

                    b.HasIndex("BasvuruId1");

                    b.ToTable("UyeIsyeriFirmaBilgi", (string)null);
                });

            modelBuilder.Entity("UyeIsyeriBasvuru.Models.UyeIsyeriKredibilite", b =>
                {
                    b.Property<long>("KredibiliteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("KredibiliteId"));

                    b.Property<decimal>("AylikYurtDisiCiro")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("AylikYurtDisiCiroParaBirimi")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<decimal>("AylikYurtIciCiro")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("AylikYurtIciCiroParaBirimi")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<long>("BasvuruId")
                        .HasColumnType("bigint");

                    b.Property<long>("BasvuruId1")
                        .HasColumnType("bigint");

                    b.Property<string>("GenelSubeGorusu")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsOlumsuzPosIstihbarat")
                        .HasColumnType("bit");

                    b.Property<string>("IsyeriFaaliyetKonusuDetay")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("KredibiliteId");

                    b.HasIndex("BasvuruId");

                    b.HasIndex("BasvuruId1");

                    b.ToTable("UyeIsyeriKredibilite", (string)null);
                });

            modelBuilder.Entity("UyeIsyeriBasvuru.Models.UyeIsyeriPosBasvuru", b =>
                {
                    b.Property<long>("PosBasvuruId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PosBasvuruId"));

                    b.Property<long>("BasvuruId")
                        .HasColumnType("bigint");

                    b.Property<long>("BasvuruId1")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDoktorPos")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMultiCurrencyPos")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOrtakPos")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTarimPos")
                        .HasColumnType("bit");

                    b.Property<bool>("IsYazarkasaPos")
                        .HasColumnType("bit");

                    b.Property<int>("MasaustuPosAdet")
                        .HasColumnType("int");

                    b.Property<string>("MisafirBanka")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MobilPosGsmAdet")
                        .HasColumnType("int");

                    b.Property<string>("PosTipi")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ToplamPosSayisi")
                        .HasColumnType("int");

                    b.Property<string>("VukMobilPosDurum")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VukSabitPosDurum")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PosBasvuruId");

                    b.HasIndex("BasvuruId");

                    b.HasIndex("BasvuruId1");

                    b.ToTable("UyeIsyeriPosBasvuru", (string)null);
                });

            modelBuilder.Entity("UyeIsyeriBasvuru.Models.UyeIsyeriPosTalep", b =>
                {
                    b.Property<long>("PosTalepId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PosTalepId"));

                    b.Property<long>("BasvuruId")
                        .HasColumnType("bigint");

                    b.Property<long>("BasvuruId1")
                        .HasColumnType("bigint");

                    b.Property<string>("KurulumAdres")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Marka")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PosAdedi")
                        .HasColumnType("int");

                    b.Property<string>("PosTipi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TalepDurumu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UrunModel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PosTalepId");

                    b.HasIndex("BasvuruId");

                    b.HasIndex("BasvuruId1");

                    b.ToTable("UyeIsyeriPosTalep", (string)null);
                });

            modelBuilder.Entity("UyeIsyeriBasvuru.Models.UyeIsyeriYetkili", b =>
                {
                    b.Property<long>("YetkiliId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("YetkiliId"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("BasvuruId")
                        .HasColumnType("bigint");

                    b.Property<long>("BasvuruId1")
                        .HasColumnType("bigint");

                    b.Property<string>("CepTelefonu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TcKimlikNo")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("YetkiTipi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("YetkiliId");

                    b.HasIndex("BasvuruId");

                    b.HasIndex("BasvuruId1");

                    b.ToTable("UyeIsyeriYetkili", (string)null);
                });

            modelBuilder.Entity("UyeIsyeriBasvuru.Models.UyeIsyeriBankaBilgi", b =>
                {
                    b.HasOne("UyeIsyeriBasvuru.Models.UyeIsyeriBasvuruModel", null)
                        .WithMany("BankaBilgileri")
                        .HasForeignKey("BasvuruId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UyeIsyeriBasvuru.Models.UyeIsyeriBasvuruModel", "Basvuru")
                        .WithMany()
                        .HasForeignKey("BasvuruId1")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Basvuru");
                });

            modelBuilder.Entity("UyeIsyeriBasvuru.Models.UyeIsyeriCalismaSarti", b =>
                {
                    b.HasOne("UyeIsyeriBasvuru.Models.UyeIsyeriBasvuruModel", null)
                        .WithMany("CalismaSartiIslemleri")
                        .HasForeignKey("BasvuruId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UyeIsyeriBasvuru.Models.UyeIsyeriBasvuruModel", "Basvuru")
                        .WithMany()
                        .HasForeignKey("BasvuruId1")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Basvuru");
                });

            modelBuilder.Entity("UyeIsyeriBasvuru.Models.UyeIsyeriDokuman", b =>
                {
                    b.HasOne("UyeIsyeriBasvuru.Models.UyeIsyeriBasvuruModel", null)
                        .WithMany("Dokumanlar")
                        .HasForeignKey("BasvuruId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UyeIsyeriBasvuru.Models.UyeIsyeriBasvuruModel", "Basvuru")
                        .WithMany()
                        .HasForeignKey("BasvuruId1")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Basvuru");
                });

            modelBuilder.Entity("UyeIsyeriBasvuru.Models.UyeIsyeriDurumLog", b =>
                {
                    b.HasOne("UyeIsyeriBasvuru.Models.UyeIsyeriBasvuruModel", null)
                        .WithMany("DurumLoglari")
                        .HasForeignKey("BasvuruId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UyeIsyeriBasvuru.Models.UyeIsyeriBasvuruModel", "Basvuru")
                        .WithMany()
                        .HasForeignKey("BasvuruId1")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Basvuru");
                });

            modelBuilder.Entity("UyeIsyeriBasvuru.Models.UyeIsyeriFirmaBilgi", b =>
                {
                    b.HasOne("UyeIsyeriBasvuru.Models.UyeIsyeriBasvuruModel", null)
                        .WithMany("FirmaBilgileri")
                        .HasForeignKey("BasvuruId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UyeIsyeriBasvuru.Models.UyeIsyeriBasvuruModel", "Basvuru")
                        .WithMany()
                        .HasForeignKey("BasvuruId1")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Basvuru");
                });

            modelBuilder.Entity("UyeIsyeriBasvuru.Models.UyeIsyeriKredibilite", b =>
                {
                    b.HasOne("UyeIsyeriBasvuru.Models.UyeIsyeriBasvuruModel", null)
                        .WithMany("KredibiliteIslemleri")
                        .HasForeignKey("BasvuruId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UyeIsyeriBasvuru.Models.UyeIsyeriBasvuruModel", "Basvuru")
                        .WithMany()
                        .HasForeignKey("BasvuruId1")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Basvuru");
                });

            modelBuilder.Entity("UyeIsyeriBasvuru.Models.UyeIsyeriPosBasvuru", b =>
                {
                    b.HasOne("UyeIsyeriBasvuru.Models.UyeIsyeriBasvuruModel", null)
                        .WithMany("PosIslemleri")
                        .HasForeignKey("BasvuruId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UyeIsyeriBasvuru.Models.UyeIsyeriBasvuruModel", "Basvuru")
                        .WithMany()
                        .HasForeignKey("BasvuruId1")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Basvuru");
                });

            modelBuilder.Entity("UyeIsyeriBasvuru.Models.UyeIsyeriPosTalep", b =>
                {
                    b.HasOne("UyeIsyeriBasvuru.Models.UyeIsyeriBasvuruModel", null)
                        .WithMany("PosTalepleri")
                        .HasForeignKey("BasvuruId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UyeIsyeriBasvuru.Models.UyeIsyeriBasvuruModel", "Basvuru")
                        .WithMany()
                        .HasForeignKey("BasvuruId1")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Basvuru");
                });

            modelBuilder.Entity("UyeIsyeriBasvuru.Models.UyeIsyeriYetkili", b =>
                {
                    b.HasOne("UyeIsyeriBasvuru.Models.UyeIsyeriBasvuruModel", null)
                        .WithMany("Yetkililer")
                        .HasForeignKey("BasvuruId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UyeIsyeriBasvuru.Models.UyeIsyeriBasvuruModel", "Basvuru")
                        .WithMany()
                        .HasForeignKey("BasvuruId1")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Basvuru");
                });

            modelBuilder.Entity("UyeIsyeriBasvuru.Models.UyeIsyeriBasvuruModel", b =>
                {
                    b.Navigation("BankaBilgileri");

                    b.Navigation("CalismaSartiIslemleri");

                    b.Navigation("Dokumanlar");

                    b.Navigation("DurumLoglari");

                    b.Navigation("FirmaBilgileri");

                    b.Navigation("KredibiliteIslemleri");

                    b.Navigation("PosIslemleri");

                    b.Navigation("PosTalepleri");

                    b.Navigation("Yetkililer");
                });
#pragma warning restore 612, 618
        }
    }
}
